remote_theme: jekyll/minima
title: Borisu's Wiki Blog
description: linux, programming, etc
date_format: "%Y-%m-%d"
header_pages:
  - about.md
  - wiki/index.md
show_downloads: false
github:
  is_project_page: false
